# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: United Parks of Jerome
email: unitedparks@gmail.com
url: "https://upj53.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: upj53

# Author settings
author:
  name: "Park Won-june"

collections:
  preparing:
    output: true
  frontpages:
    output: false
  para-projects:
    output: true
  para-area:
    output: true
  para-resource:
    output: true
  para-archive:
    output: true

defaults:
  - scope:
      path: "para"
      type: "posts"
    values:
      layout: "upj_design"

# social settings
og_locale: "ko_kr"

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-sitemap

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
    line_numbers: false
  input: GFM
  auto_ids: false
  toc_levels: 2..3
  parse_block_html: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - nohup.out
  - goorm.manifest
